CFLAGS=-Wall -Wpedantic -Wextra -O2 -std=c11 -g
CC=clang

fibheaptest.o: ../bspfibheap.h

all: avltest fibheaptest regexptest dijkstra prim

clean:
	rm -f *.o avltest fibheaptest regexptest dijkstra prim primfull dijkstrafull

.PHONY: clean man
