CFLAGS=-Wall -Wpedantic -Wextra -std=c11 -g
CC=clang

all: avltest fibheaptest

avltest: avltest.o

fibheaptest: fibheaptest.o

dijkstra: dijkstra.o

clean:
	rm -f *.o avltest fibheaptest dijkstra

.PHONY: clean man
